name: Build and Upload Artifact

on:
  push:
    branches:
      - executor
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: executor

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          chmod +x "installResources.sh"
          "installResources.sh"
      - name: Build executable
        run: pyinstaller --onefile --hidden-import=yaml,xmltodict ui_async_version.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: application
          path: dist/main.exe
